name = "gleamc"
version = "1.0.0"

description = "Compiler for subset of Gleam written in Gleam"
licences = ["MIT"]
repository = { type = "github", user = "leszkolukasz", repo = "gleam-in-gleam" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
clip = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
spinner = ">= 1.3.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
